### ISSUE TITLE
YouTube streaming

### ISSUE THREAD

**Issue by Phoenixness** [appellation/pleb#49]
Bot disconnects from voice chat a second after playing a YouTube stream

**Comment by appellation** [comment]
The bot is designed to disconnect after the playlist is finished, whether that playlist is 1 song or 200 songs long.  However, if you're seeing the bot disconnect a couple seconds after _starting_ a stream, a bit more info around the problem would be great.  I can't reproduce it: playing YouTube audio works just fine for me.

If you would like the bot to remain connected after streaming, just clarify that that's what you're looking for and I'll look into it.

**Comment by Phoenixness** [comment]
Thanks for the fast response.

It would be preferable if the bot didn't disconnect when finished.

The issue we found was when we asked the bot to play YouTube live streams such as with '@pleb play monstercat' it would open this link: https://youtu.be/4R-JGw3VTuY it would then disconnect after a short amount of time

**Comment by appellation** [comment]
Unfortunately I can't find a way to actually play live streams right now.  I'll look into in in the future, but for now querying `monstercat` should just play the first actual video matching that query.

**Comment by Phoenixness** [comment]
Alright, thank you for your work. Ill look forward to future updates.
