### ISSUE TITLE
Youtube playlists won't go past the 2nd song

### ISSUE THREAD

**Issue by supermikes** [appellation/pleb#69]
Hey, every time I enter a youtube playlist it won't go past the 2nd song. 

For example I type 
@Pleb#5710 play https://www.youtube.com/playlist?list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG

and it won't play past song 2. I don't know if this will be reproducible on your machine. If it isn't is there any troubleshooting I can do to fix the bot on my server?

**Comment by appellation** [comment]
lol fml.  I'll see what I can do.
